<a href="https://colab.research.google.com/github/amirsharifi74/cat-vs-dog-keras/blob/master/Cat_vs_dog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Frist Preproccecing Data

In [3]:
#@title mount google drive
from google.colab import drive
drive.mount('/content/amirdrive')

Drive already mounted at /content/amirdrive; to attempt to forcibly remount, call drive.mount("/content/amirdrive", force_remount=True).


In [4]:
import numpy as np
import os
import keras
import cv2
import tqdm
import random
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [6]:
DATA_DIR = '/content/amirdrive/My Drive/Document/Database'
CATEGORIES = ['Dog','Cat']
IMG_SIZE = 60
training_data = []


def creat_training_data():
  
  for categories in CATEGORIES:
    print('1')
    path = os.path.join(DATA_DIR,categories)
    class_num = CATEGORIES.index(categories)
    for img in tqdm.tqdm(os.listdir(path)):
      try:
        img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
        
        
      except Exeption as e:
        pass

    
creat_training_data()

  0%|          | 0/511 [00:00<?, ?it/s]

1
[[137 137 137 ... 139 139 139]
 [137 137 137 ... 143 143 143]
 [137 137 137 ... 136 136 136]
 ...
 [ 91  91  92 ...  70  70  70]
 [ 92  92  93 ...  70  69  69]
 [ 93  93  94 ...  69  68  68]]
